### ISSUE TITLE
Issue with lockscreen on resuming from suspend

### ISSUE THREAD

**Issue by jdtanner** [linuxmint/cinnamon-screensaver#342]
```
 * Cinnamon-Screensaver version (cinnamon-screensaver --version): 4.6.0
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 20
 * Graphics hardware *and* driver used:

Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Xiaomi driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:1916 
           Device-2: NVIDIA GM108M [GeForce 940MX] vendor: Xiaomi driver: nvidia v: 440.100 
           bus ID: 01:00.0 chip ID: 10de:134b 
           Display: x11 server: X.Org 1.20.8 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 20.0.8 
           direct render: Yes 

 * 32 or 64 bit: 64 bit
 ```

**Issue**
Taken from: https://forums.linuxmint.com/viewtopic.php?p=1842818#p1842818

_I've found that Linux Mint 20, after i suspend the laptop by closing the lid and i have actived the screensaver (and lock screen) after suspend, the screensaver isn't showed, nor the box for introduce user/pass, the cinnamon desktop is showed and i can move the mouse, but i cann't do anything more... nothing is running after suspend with screensaver activated (lock screen) after suspend._

To add to the above, blindly typing your password and pressing enter will present you with a functional desktop. There are multiple other reports of similar behaviour on the forums, but nobody appears to have posted a bug report. 

**Steps to reproduce**

- Allow laptop to enter suspend.
- Wake laptop from suspend.
- Desktop is displayed rather than lockscreen, but is not interactive other than the mouse cursor being moveable.
- Blindly typing password and pressing enter restores functional desktop.

**Expected behaviour**

Upon waking from suspend,  interactive lockscreen should be presented. 

**Other information**

System logs seem to be catching the following error from cinnamon-screensaver (screenshot below):

`pam_ecryptfs: seteuid error`

![Screenshot from 2020-07-09 21-08-18](https://user-images.githubusercontent.com/1623591/87134975-52989800-c291-11ea-9a28-e3d908597589.png)

**Comment by Mintulix** [comment]
It's here again... #288 #289

**Comment by leigh123linux** [comment]
Duplicate.

**Comment by jdtanner** [comment]
I'm a little confused...what is it a duplicate of? 288 and 289 are both closed?

**Comment by Mintulix** [comment]
Hi @leigh123linux, you misunderstood my comment. This is not duplicate. It's an ancient error that was fixed a long time ago and now reappeared in LM20. At least it _seems_ to be the same error. Please reopen it.
Log in is invisible when suspend was started by closing the notebook lid.

**Comment by leigh123linux** [comment]
Try removing ecryptfs-utils, it breaks almost all screensavers

https://bugs.launchpad.net/ubuntu/+source/gnome-screensaver/+bug/1085706

**Comment by mtwebster** [comment]
The setuid error is old and unrelated to this current issue.

Can you run:
```
dconf dump /org/cinnamon/ > some_filename
```
and pastebin the file?  Redact any personal info if you'd like.  I mainly want to look at power and screensaver settings.

The screensaver has had pretty much no changes from 4.4->4.6, other than build-related things, but I'll have a look at that as well, just in case.

**Comment by mtwebster** [comment]
Can you guys also let me know how you got to Mint 20 - upgrade or fresh install.  Thanks

**Comment by jdtanner** [comment]
Hi there,

dconf output attached

Fresh install of Mint 20. I am running the latest mainline kernel, but the same issue happens with the current Mint kernel. 

[dconf.txt](https://github.com/linuxmint/cinnamon-screensaver/files/4907514/dconf.txt)

**Comment by Mintulix** [comment]
@leigh123linux I removed ecryptfs-utils, restarted notebook, closed lid, opend it up again after a few seconds - and both errors were gone:
- no more pam_ecryptfs: seteuid error
- login visible as usual

@jdtanner please check this also to be sure.

@mtwebster It was an upgrade from LM 19.3 with Clem's tutorial. If ecryptfs-utils is the culprit, you could install it yourself and see what's happening.

I don't know if I installed ecryptfs-utils by myself or if it's in the normal install. I used to encrypt a single folder in /home with ecryptfs but switched to gocryptfs a while ago...

**Comment by mtwebster** [comment]
It is installed, but I can't reproduce this.

**Comment by Mintulix** [comment]
Hmmm, I reinstalled ecryptfs-utils to countercheck:
- pam_ecryptfs: seteuid error is here again, so this one should be solved
- no problem with login after suspend, so I don't know what caused this. I tested a few times - no error. We have to wait for others...
[dconf_cin.txt](https://github.com/linuxmint/cinnamon-screensaver/files/4907560/dconf_cin.txt)

**Comment by mtwebster** [comment]
Is your home encrypted?

**Comment by Mintulix** [comment]
/home is not encrypted, just a single folder in /home/... with gocryptfs

**Comment by jdtanner** [comment]
No encryption here...standard install only.

**Comment by Mintulix** [comment]
I didn't had the invisible login error since 2 days. Could it have been fixed by cinnamon-desktop 4.6.3? Perhaps I didn't restart my notebook after the update immediately, so I saw the effect one day later...
Whatever the reason is - for me this seems to be gone on both notebooks.

**Comment by davidgfnet** [comment]
Hey there!
Just wanted to report that this happens to me as well, using Fedora 32, so I suspect is not a Mint specific issue. I do not have any weird things installed so far, it happened pretty much since the fresh install. My cinnamon version is 4.6.5 and I have a Dell XPS9350.

**Comment by alsar** [comment]
It seems that this is not happening anymore on Cinnamon 4.6.6.

**Comment by davidgfnet** [comment]
I updated to 4.6.6 a couple days ago IIRC. Still happening. In Fedora cinnamon-screensaver is at 4.6.0-1 version, which seems the latest version in this repo (there's only 2 commits after that tag).

**Comment by areographe** [comment]
I'm using Cinnamon 4.6.6 on Manjaro and the same problem has just started occurring for me. 

```
Cinnamon-screensaver version: 4.6.0
Distribution: Manjaro Cinnamon

Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Lenovo driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:1916 
           Display: x11 server: X.Org 1.20.8 driver: intel unloaded: modesetting 
           alternate: fbdev,vesa resolution: 1920x1080~60Hz, 2560x1440~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 20.1.3 
           direct render: Yes 
```

switching to tty2 and then back 'solves' it, but it happens every time my screen locks, either as part of the screensaver or if I manually lock it.

**Comment by silocoder** [comment]
`cinnamon-screensaver-pam-helper: pam_ecryptfs: seteuid error`

I reproduce the same error by just doing 
`tail -f /var/log/syslog`
and in another terminal
`cinnamon-screensaver-command -a`
and log back in.

Though I don't have any issues with functionality.

**Comment by davidgfnet** [comment]
Just noting here that I doi not use any type of ecryptfs or similar software.

**Comment by tkhyn** [comment]
Hi, I can confirm the same observations as @Mintulix on Cinnamon 4.6.7 after a manual upgrade from 19.3 (mintupgrade did not work, I ran into https://github.com/linuxmint/mintupgrade/issues/27), on a LUKS encrypted partition. Login screen was frozen on resume. ``apt remove ecryptfs-utils`` fixed it, and after ``apt install ecryptfs-utils`` it still worked...

**Comment by jasmith79** [comment]
Experiencing this issue. Fresh install of linux mint 20, cinnamon 4.6.7, kernel 5.4.0-48. Ran system update, rebooted, same problem. Removed ecryptfs-utils, rebooted, same problem. Every time I close the lid unless I manually suspend first. Laptop is an HP zbook if that matters.

**Comment by xavxa** [comment]
Hi, same problem.
Kernel: 5.8.0-23-generic x86_64 bits: 64 Desktop: Cinnamon 4.6.7 wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

**Comment by astromatt42** [comment]
I am experiencing the same issue in LM 20 Kernel 5.4.0.-52. This seems to be a problem with rendering the lock screen. If I either type in my password blindly or I hover the mouse over the part of the screen where the password box would be, I get a cursor and can enter the password that way.

**Comment by GopherJ** [comment]
I'm experincing this issue as well in HW matebook x pro Kernel 5.4.0-60

**Comment by aspi66** [comment]
> I'm experincing this issue as well in HW matebook x pro Kernel 5.4.0-60, I can fix it by hitting laptop's poweroff button, then it doesn't freeze anymore, I can then choose `no` to not shutdown/reboot
> 
> [#342 (comment)](https://github.com/linuxmint/cinnamon-screensaver/issues/342#issuecomment-657100802) doesn't work for me

My situation is the same, same machine. Kernel 5.4.0-65. I've just got used briefly changing screen brightness up and back down using hotkeys. So I guess the issue is something related to rerendering process.

**Comment by sdlambert** [comment]
I experienced this issue for quite some time on Mint 19.3 and it continues today. I'll happily offer my logs if it will help.

**Comment by SeaMonkey82** [comment]
Linux Mint 20.2 (upgrade)
```
│Oct 31 15:04:29 earth cinnamon-screensaver-pam-helper: pam_ecryptfs: seteuid error                                                                                                                                                                                                                                                                                                                                                                                                          │
│Oct 31 15:04:39 earth cinnamon-session[6207]: WARNING: t+42973.27058s: Detected that screensaver has left the bus                                                                                                                                                                                                                                                                                                                                                                           │
│Oct 31 15:04:39 earth org.cinnamon.ScreenSaver[15028]: Trying to connect to logind...                                                                                                                                                                                                                                                                                                                                                                                                       │
│Oct 31 15:04:39 earth org.cinnamon.ScreenSaver[15028]: Starting screensaver...                                                                                                                                                                                                                                                                                                                                                                                                              │
│Oct 31 15:04:39 earth org.cinnamon.ScreenSaver[15028]: Cinnamon Screensaver support not found in current theme - adding some...                                                                                                                                                                                                                                                                                                                                                             │
│Oct 31 15:04:39 earth org.cinnamon.ScreenSaver[15028]: Successfully using logind                                                                                                                                                                                                                                                                                                                                                                                                            │
│Oct 31 15:04:39 earth org.cinnamon.ScreenSaver[15028]: Error in sys.excepthook:                                                                                                                                                                                                                                                                                                                                                                                                             │
│Oct 31 15:04:39 earth org.cinnamon.ScreenSaver[15028]: Original exception was:                                                                                                                                                                                                                                                                                                                                                                                                              │
│Oct 31 15:04:39 earth org.cinnamon.ScreenSaver[15028]: Error in sys.excepthook:                                                                                                                                                                                                                                                                                                                                                                                                             │
│Oct 31 15:04:39 earth org.cinnamon.ScreenSaver[15028]: Original exception was:                                                                                                                                                                                                                                                                                                                                                                                                              │
│Oct 31 15:04:39 earth org.cinnamon.ScreenSaver[15028]: Error in sys.excepthook:                                                                                                                                                                                                                                                                                                                                                                                                             │
│Oct 31 15:04:39 earth org.cinnamon.ScreenSaver[15028]: Original exception was:                                                                                                                                                                                                                                                                                                                                                                                                              │
│Oct 31 15:09:01 earth CRON[111148]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)    `
```

[dconf.txt](https://github.com/linuxmint/cinnamon-screensaver/files/7449645/dconf.txt)

**Comment by EricVanCaenenberghe** [comment]
The oldest occurrence in my logs dates from 8 November 2021 (Linux Mint 20.2), still present today Mint 20.3.
Log detail
![details log](https://user-images.githubusercontent.com/29582047/151576732-60f3631e-8b6b-4e19-9943-edf6d8e716ab.png)
System information
![system info](https://user-images.githubusercontent.com/29582047/151576843-2cbb10f0-5639-41c2-b63b-9d206bc069d0.png)
result dconf dump
[result dconf dump cinnamon.txt](https://github.com/linuxmint/cinnamon-screensaver/files/7959914/result.dconf.dump.cinnamon.txt)

**Comment by Melaron** [comment]
I believe that I have encountered the same issue. Lock screen appears invisible but blind typing password allows me to unlock.

Some of my system info:
```
Linux Mint 21.3 Virginia
cinnamon-screensaver 6.0.3
kernel: 5.15.0-113-generic
```

 `journalctl` entries after waking my laptop up:
```
Jul 10 12:10:35 melaron-NS5x-NS7xPU cinnamon-screensaver-pam-helper[100152]: pam_ecryptfs: seteuid error
Jul 10 12:10:35 melaron-NS5x-NS7xPU cinnamon-screensaver-pam-helper[100152]: gkr-pam: unlocked login keyring
Jul 10 12:10:49 melaron-NS5x-NS7xPU wpa_supplicant[952]: wlp43s0: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-51 noise=9999 txrate=216000
Jul 10 12:11:05 melaron-NS5x-NS7xPU org.cinnamon.ScreenSaver[99955]: AccountsService ready
Jul 10 12:11:05 melaron-NS5x-NS7xPU cinnamon-session[3299]: WARNING: t+21272.30494s: Detected that screensaver has left the bus
Jul 10 12:11:05 melaron-NS5x-NS7xPU org.cinnamon.ScreenSaver[99955]: Error in sys.excepthook:
Jul 10 12:11:05 melaron-NS5x-NS7xPU org.cinnamon.ScreenSaver[99955]: Original exception was:
Jul 10 12:11:05 melaron-NS5x-NS7xPU org.cinnamon.ScreenSaver[99955]: Error in sys.excepthook:
Jul 10 12:11:05 melaron-NS5x-NS7xPU org.cinnamon.ScreenSaver[99955]: Original exception was:
Jul 10 12:11:05 melaron-NS5x-NS7xPU org.cinnamon.ScreenSaver[99955]: Error in sys.excepthook:
Jul 10 12:11:05 melaron-NS5x-NS7xPU org.cinnamon.ScreenSaver[99955]: Original exception was:
```

Using the shortcut `Ctrl+Alt+L` to lock the screen and unlock also causes this repeatably. 

Possibly relevant:
- My home folder is encrypted
- This issue only occurred after I copy-pasted my Linux Mint partition (to "jump" my Windows partition and get to unallocated space)
- I used `ecryptfs-unwrap-passphrase` for the first time during this process

Please let me know if I can provide more information or help in any way. Thank you for your efforts thus far, @mtwebster and everyone else who has worked on this.

**Comment by Szili007** [comment]
So to help others:

I have searched a solution for linux lite (ubuntu xfce) to fix this error:
https://forums.linuxmint.com/viewtopic.php?t=375679

(When my computer goes to the screensaver (blank - black) and then I shake the mouse, it opens up without the sign-in box. This is expected behavior for me since I have these settings in Menu - Screensaver:  --lock screen when laptop lid closed)

And I unexpectedly fixed it. I changed in xfce4-screensaver the theme to a GL theme (GL Matrix). And for some reason GL themes works good.

(1 extra thing: if you close the lid and you immediately open it (so as fast as you can, but you wait until the monitor switches off, than you open it as fast as you can) than every theme should work. And after you close the lid for long time, after you open again it will work)
